# Generated by Django 2.2.3 on 2019-07-28 02:13

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Shipping to? Who is it for?', max_length=120, null=True)),
                ('address_line_1', models.CharField(max_length=120)),
                ('address_line_2', models.CharField(blank=True, help_text='Drag the marker to your location', max_length=120, null=True)),
                ('postal_code', models.CharField(max_length=10)),
                ('far', models.BooleanField(default=True, help_text='shipping charge will be added')),
                ('latitude', models.CharField(blank=True, default='50.830149', max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, default='4.385636', max_length=50, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile')),
            ],
        ),
    ]
